
CREATE TABLE IF NOT EXISTS auth (
  id SERIAL PRIMARY KEY ,
  password VARCHAR(255) not NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(255) not NULL,
  last_name VARCHAR(255) not NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  is_staff BOOLEAN NOT NULL,
  auth_id__id INTEGER REFERENCES auth
);
