module RestEntities.HasDataProvider.HasDataProvider
(module RestEntities.HasDataProvider.Internal.HasFilterableDataProvider,
 module RestEntities.HasDataProvider.Internal.HasLoadableDataProvider,
 module RestEntities.HasDataProvider.Internal.HasSaveableDataProvider,
 module RestEntities.HasDataProvider.Internal.HasDeleteableDataProvider,
 module RestEntities.HasDataProvider.Internal.HasDataProvider) where

import RestEntities.HasDataProvider.Internal.HasFilterableDataProvider
import RestEntities.HasDataProvider.Internal.HasLoadableDataProvider
import RestEntities.HasDataProvider.Internal.HasSaveableDataProvider
import RestEntities.HasDataProvider.Internal.HasDeleteableDataProvider
import RestEntities.HasDataProvider.Internal.HasDataProvider